name: Deploy to GitHub Pages

on:
  push:
    branches:
      - dev # replace with your default branch if not 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.102 # replace with your .NET version

      - name: Build and deploy Statiq site
        uses: Statiqdev/gha-statiq@main
        with:
          args: build --deploy --deployBranchName "gh-pages" --deployPersonalAccessToken ${{ secrets.GITHUB_TOKEN }}        