name: Deploy Site

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '3.1.100' # SDK Version to use.
    - name: Set working directory
      run: cd VanillaPlusWebsite
    - run: dotnet run -- deploy --root VanillaPlusWebsite
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
